version: '3'
services:
  web:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      SECRET_KEY: 9a55af0d1581c5f131b6
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ssd_database
      MYSQL_USER: ssd_user
      MYSQL_PASSWORD: ssd_password
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
