version: "3.7"

services:
  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp
    volumes:
      - dbdata:/var/lib/mysql
    restart: unless-stopped

  wp:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wp
      WORDPRESS_DB_NAME: wp
      SITE_URL: "http://web.ssdc.ac:24657/"
      # FLAG 환경변수 미지정 시 기본값 사용(SSD{...})
      # FLAG: "SSD{custom_flag_here}
      FLAG: "SSD{yeeee_eeeeeee_eyyyy_yy_yyyyyy}"
    ports:
      - "24657:80"   # 요구사항: 외부 포트 20000~30000
    restart: unless-stopped

volumes:
  dbdata:
